# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first) = Word.create(title: "lamp" ,letter_count: 4)
w1 = Word.create(title: "sale",letter_count: 4)
w2 = Word.create(title: "stir",letter_count: 4)
w3 = Word.create(title: "brag",letter_count: 4)
w4 = Word.create(title: "cart",letter_count: 4)
w5 = Word.create(title: "line",letter_count: 4)
w6 = Word.create(title: "core",letter_count: 4)
w7 = Word.create(title: "mind",letter_count: 4)
w8 = Word.create(title: "user",letter_count: 4)
w9 = Word.create(title: "keep",letter_count: 4)

w10 = Word.create(title: "tight",letter_count: 5)
w11 = Word.create(title: "catch",letter_count: 5)
w12 = Word.create(title: "robot",letter_count: 5)
w13 = Word.create(title: "blast",letter_count: 5)
w14 = Word.create(title: "brick",letter_count: 5)
w15 = Word.create(title: "radio",letter_count: 5)
w16 = Word.create(title: "noise",letter_count: 5)
w17 = Word.create(title: "ideal",letter_count: 5)
w18 = Word.create(title: "basin",letter_count: 5)

w19 = Word.create(title: "scheme",letter_count: 6)
w20 = Word.create(title: "polite",letter_count: 6)
w21 = Word.create(title: "rivive",letter_count: 6)
w22 = Word.create(title: "virgin",letter_count: 6)
w23 = Word.create(title: "spider",letter_count: 6)
w24 = Word.create(title: "common",letter_count: 6)
w25 = Word.create(title: "unfair",letter_count: 6)
w26 = Word.create(title: "clique",letter_count: 6)
w27 = Word.create(title: "absorb",letter_count: 6)

p1 = Player.create(name: "Girija")
p2 = Player.create(name: "Bronte")
p3 = Player.create(name: "Brooke")
p4 = Player.create(name: "Aaron")
p5 = Player.create(name: "Jason")
p6 = Player.create(name: "Donny")
p7 = Player.create(name: "Amelie")

pg1 = PlayedGame.create(score: 16, word: w1, player: p1)
pg2 = PlayedGame.create(score: 23, word: w2, player: p2)
pg3 = PlayedGame.create(score: 9, word: w3, player: p3)
pg4 = PlayedGame.create(score: 13, word: w4, player: p4)
pg5 = PlayedGame.create(score: 13, word: w5, player: p5)
pg6 = PlayedGame.create(score: 4, word: w6, player: p6)
pg7 = PlayedGame.create(score: 22, word: w11, player: p7)
pg8 = PlayedGame.create(score: 35, word: w14, player: p2)
pg9 = PlayedGame.create(score: 31, word: w25, player: p3)

pgw1 = PlayedGameWord.create(played_game: pg1, word: w1)
pgw2 = PlayedGameWord.create(played_game: pg2, word: w2)
pgw3 = PlayedGameWord.create(played_game: pg3, word: w3)
pgw4 = PlayedGameWord.create(played_game: pg4, word: w4)
pgw5 = PlayedGameWord.create(played_game: pg5, word: w5)
pgw6 = PlayedGameWord.create(played_game: pg6, word: w6)
pgw7 = PlayedGameWord.create(played_game: pg7, word: w11)
pgw8 = PlayedGameWord.create(played_game: pg8, word: w14)
pgw9 = PlayedGameWord.create(played_game: pg9, word: w25)

