# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first) = Word.create(title: "lamp" ,letter_count: 4)


#4 letter words
w1 = Word.create(title: "sale",letter_count: 4)
w2 = Word.create(title: "stir",letter_count: 4)
w3 = Word.create(title: "brag",letter_count: 4)
w4 = Word.create(title: "cart",letter_count: 4)
w5 = Word.create(title: "line",letter_count: 4)
w6 = Word.create(title: "core",letter_count: 4)
w7 = Word.create(title: "mind",letter_count: 4)
w8 = Word.create(title: "user",letter_count: 4)
w9 = Word.create(title: "keep",letter_count: 4)
Word.create(title: "stew",letter_count: 4)
Word.create(title: "leap",letter_count: 4)
Word.create(title: "jeep",letter_count: 4)
Word.create(title: "kelp",letter_count: 4)
Word.create(title: "melt",letter_count: 4)
Word.create(title: "belt",letter_count: 4)
Word.create(title: "felt",letter_count: 4)
Word.create(title: "sill",letter_count: 4)
Word.create(title: "mill",letter_count: 4)
Word.create(title: "will",letter_count: 4)
Word.create(title: "pill",letter_count: 4)
Word.create(title: "jill",letter_count: 4)
Word.create(title: "kill",letter_count: 4)
Word.create(title: "hill",letter_count: 4)
Word.create(title: "nill",letter_count: 4)
Word.create(title: "func",letter_count: 4)
Word.create(title: "part",letter_count: 4)
Word.create(title: "lark",letter_count: 4)
Word.create(title: "mall",letter_count: 4)
Word.create(title: "tall",letter_count: 4)
Word.create(title: "dunk",letter_count: 4)
Word.create(title: "lunk",letter_count: 4)
Word.create(title: "plum",letter_count: 4)
Word.create(title: "drum",letter_count: 4)
Word.create(title: "scum",letter_count: 4)
Word.create(title: "make",letter_count: 4)
Word.create(title: "take",letter_count: 4)
Word.create(title: "lake",letter_count: 4)
Word.create(title: "fake",letter_count: 4)
Word.create(title: "nape",letter_count: 4)
Word.create(title: "nick",letter_count: 4)
Word.create(title: "boot",letter_count: 4)
Word.create(title: "toot",letter_count: 4)
Word.create(title: "loot",letter_count: 4)
Word.create(title: "moot",letter_count: 4)
Word.create(title: "plop",letter_count: 4)
Word.create(title: "blob",letter_count: 4)








#5 letter words
w10 = Word.create(title: "tight",letter_count: 5)
w11 = Word.create(title: "catch",letter_count: 5)
w12 = Word.create(title: "robot",letter_count: 5)
w13 = Word.create(title: "blast",letter_count: 5)
w14 = Word.create(title: "brick",letter_count: 5)
w15 = Word.create(title: "radio",letter_count: 5)
w16 = Word.create(title: "noise",letter_count: 5)
w17 = Word.create(title: "ideal",letter_count: 5)
w18 = Word.create(title: "basin",letter_count: 5)
Word.create(title: "tight",letter_count: 5)
Word.create(title: "catch",letter_count: 5)
Word.create(title: "robot",letter_count: 5)
Word.create(title: "blast",letter_count: 5)
Word.create(title: "brick",letter_count: 5)
Word.create(title: "radio",letter_count: 5)
Word.create(title: "noise",letter_count: 5)
Word.create(title: "ideal",letter_count: 5)
Word.create(title: "basin",letter_count: 5)
Word.create(title: "cabin",letter_count: 5)
Word.create(title: "start",letter_count: 5)
Word.create(title: "pluck",letter_count: 5)
Word.create(title: "jesus",letter_count: 5)
Word.create(title: "quote",letter_count: 5)
Word.create(title: "drink",letter_count: 5)
Word.create(title: "witch",letter_count: 5)
Word.create(title: "whore",letter_count: 5)
Word.create(title: "dad??",letter_count: 5)
Word.create(title: "thumb",letter_count: 5)
Word.create(title: "booze",letter_count: 5)
Word.create(title: "drugs",letter_count: 5)
Word.create(title: "booby",letter_count: 5)
Word.create(title: "chode",letter_count: 5)
Word.create(title: "taint",letter_count: 5)
Word.create(title: "grace",letter_count: 5)
Word.create(title: "fisty",letter_count: 5)
Word.create(title: "semen",letter_count: 5)
Word.create(title: "balls",letter_count: 5)
Word.create(title: "award",letter_count: 5)
Word.create(title: "learn",letter_count: 5)
Word.create(title: "demon",letter_count: 5)
Word.create(title: "troll",letter_count: 5)
Word.create(title: "kroll",letter_count: 5)
Word.create(title: "coach",letter_count: 5)
Word.create(title: "roach",letter_count: 5)
Word.create(title: "toast",letter_count: 5)








#6 letter words
Word.create(title: "scheme",letter_count: 6)
Word.create(title: "polite",letter_count: 6)
Word.create(title: "rivive",letter_count: 6)
Word.create(title: "virgin",letter_count: 6)
Word.create(title: "spider",letter_count: 6)
Word.create(title: "common",letter_count: 6)
Word.create(title: "unfair",letter_count: 6)
Word.create(title: "clique",letter_count: 6)
Word.create(title: "absorb",letter_count: 6)
Word.create(title: "vagina",letter_count: 6)
Word.create(title: "trumpe",letter_count: 6)
Word.create(title: "blammy",letter_count: 6)
Word.create(title: "trampy",letter_count: 6)
Word.create(title: "slammy",letter_count: 6)
Word.create(title: "fanned",letter_count: 6)
Word.create(title: "rammed",letter_count: 6)
Word.create(title: "clappy",letter_count: 6)
Word.create(title: "slappy",letter_count: 6)
Word.create(title: "flappy",letter_count: 6)
Word.create(title: "scrapp",letter_count: 6)
Word.create(title: "kaplow",letter_count: 6)
Word.create(title: "placed",letter_count: 6)
Word.create(title: "crepes",letter_count: 6)
Word.create(title: "waterd",letter_count: 6)
Word.create(title: "coffee",letter_count: 6)
Word.create(title: "errors",letter_count: 6)
Word.create(title: "timing",letter_count: 6)
Word.create(title: "possum",letter_count: 6)
Word.create(title: "shlosh",letter_count: 6)
Word.create(title: "scores",letter_count: 6)
Word.create(title: "smoked",letter_count: 6)
Word.create(title: "heroin",letter_count: 6)
Word.create(title: "cracky",letter_count: 6)
Word.create(title: "slight",letter_count: 6)
Word.create(title: "player",letter_count: 6)
Word.create(title: "panned",letter_count: 6)
Word.create(title: "crummy",letter_count: 6)
Word.create(title: "lamest",letter_count: 6)
Word.create(title: "pagent",letter_count: 6)
Word.create(title: "bronte",letter_count: 6)
Word.create(title: "smokey",letter_count: 6)
Word.create(title: "hungry",letter_count: 6)
Word.create(title: "wework",letter_count: 6)
Word.create(title: "porked",letter_count: 6)
Word.create(title: "condom",letter_count: 6)
Word.create(title: "donkey",letter_count: 6)
Word.create(title: "cranky",letter_count: 6)
Word.create(title: "shakey",letter_count: 6)
Word.create(title: "shakem",letter_count: 6)
Word.create(title: "gottem",letter_count: 6)

# 7 letters
Word.create(title: "limited",letter_count: 7)
Word.create(title: "horizon",letter_count: 7)
Word.create(title: "parking",letter_count: 7)
Word.create(title: "welcome",letter_count: 7)
Word.create(title: "nuclear",letter_count: 7)
Word.create(title: "stumble",letter_count: 7)
Word.create(title: "exploit",letter_count: 7)
Word.create(title: "extract",letter_count: 7)
Word.create(title: "related",letter_count: 7)
Word.create(title: "thought",letter_count: 7)
Word.create(title: "contact",letter_count: 7)
Word.create(title: "diagram",letter_count: 7)
Word.create(title: "laundry",letter_count: 7)
Word.create(title: "liberty",letter_count: 7)
Word.create(title: "squeeze",letter_count: 7)
Word.create(title: "gradual",letter_count: 7)
Word.create(title: "clubrat",letter_count: 7)
Word.create(title: "blasted",letter_count: 7)
Word.create(title: "ouchies",letter_count: 7)
Word.create(title: "sotired",letter_count: 7)
Word.create(title: "flatten",letter_count: 7)
Word.create(title: "condone",letter_count: 7)
Word.create(title: "crybaby",letter_count: 7)
Word.create(title: "tinyted",letter_count: 7)
Word.create(title: "frontin",letter_count: 7)
Word.create(title: "bologna",letter_count: 7)
Word.create(title: "welfare",letter_count: 7)
Word.create(title: "scatter",letter_count: 7)
Word.create(title: "passive",letter_count: 7)
Word.create(title: "pottery",letter_count: 7)



#players
p1 = Player.create(name: "Girija")
p2 = Player.create(name: "Bronte")
p3 = Player.create(name: "Brooke")
p4 = Player.create(name: "Aaron")
p5 = Player.create(name: "Jason")
p6 = Player.create(name: "Donny")
p7 = Player.create(name: "Amelie")


#games
g1 = Game.create(score: 16, player: p1)
g2 = Game.create(score: 23, player: p2)
g3 = Game.create(score: 9, player: p3)
g4 = Game.create(score: 13, player: p4)
g5 = Game.create(score: 13, player: p5)
g6 = Game.create(score: 4, player: p6)
g7 = Game.create(score: 22, player: p7)
g8 = Game.create(score: 35, player: p2)
g9 = Game.create(score: 31, player: p3)


#gamewords
gw1 = GameWord.create(game: g1, word: w1)
gw2 = GameWord.create(game: g2, word: w2)
gw3 = GameWord.create(game: g3, word: w3)
gw4 = GameWord.create(game: g4, word: w4)
gw5 = GameWord.create(game: g5, word: w5)
gw6 = GameWord.create(game: g6, word: w6)
gw7 = GameWord.create(game: g7, word: w11)
gw8 = GameWord.create(game: g8, word: w14)


