# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first) = Word.create(title: "lamp" ,letter_count: 4)
w1 = Word.create(title: "sale",letter_count: 4)
w2 = Word.create(title: "stir",letter_count: 4)
w3 = Word.create(title: "brag",letter_count: 4)
w4 = Word.create(title: "cart",letter_count: 4)
w5 = Word.create(title: "line",letter_count: 4)
w6 = Word.create(title: "core",letter_count: 4)
w7 = Word.create(title: "mind",letter_count: 4)
w8 = Word.create(title: "user",letter_count: 4)
w9 = Word.create(title: "keep",letter_count: 4)

w10 = Word.create(title: "tight",letter_count: 5)
w11 = Word.create(title: "catch",letter_count: 5)
w12 = Word.create(title: "robot",letter_count: 5)
w13 = Word.create(title: "blast",letter_count: 5)
w14 = Word.create(title: "brick",letter_count: 5)
w15 = Word.create(title: "radio",letter_count: 5)
w16 = Word.create(title: "noise",letter_count: 5)
w17 = Word.create(title: "ideal",letter_count: 5)
w18 = Word.create(title: "basin",letter_count: 5)

w19 = Word.create(title: "scheme",letter_count: 6)
w20 = Word.create(title: "polite",letter_count: 6)
w21 = Word.create(title: "rivive",letter_count: 6)
w22 = Word.create(title: "virgin",letter_count: 6)
w23 = Word.create(title: "spider",letter_count: 6)
w24 = Word.create(title: "common",letter_count: 6)
w25 = Word.create(title: "unfair",letter_count: 6)
w26 = Word.create(title: "clique",letter_count: 6)
w27 = Word.create(title: "absorb",letter_count: 6)

p1 = Player.create(name: "Girija")
p2 = Player.create(name: "Bronte")
p3 = Player.create(name: "Brooke")
p4 = Player.create(name: "Aaron")
p5 = Player.create(name: "Jason")
p6 = Player.create(name: "Donny")
p7 = Player.create(name: "Amelie")

g1 = Game.create(score: 16, player: p1)
g2 = Game.create(score: 23, player: p2)
g3 = Game.create(score: 9, player: p3)
g4 = Game.create(score: 13, player: p4)
g5 = Game.create(score: 13, player: p5)
g6 = Game.create(score: 4, player: p6)
g7 = Game.create(score: 22, player: p7)
g8 = Game.create(score: 35, player: p2)
g9 = Game.create(score: 31, player: p3)

gw1 = GameWord.create(game: g1, word: w1)
gw2 = GameWord.create(game: g2, word: w2)
gw3 = GameWord.create(game: g3, word: w3)
gw4 = GameWord.create(game: g4, word: w4)
gw5 = GameWord.create(game: g5, word: w5)
gw6 = GameWord.create(game: g6, word: w6)
gw7 = GameWord.create(game: g7, word: w11)
gw8 = GameWord.create(game: g8, word: w14)
gw9 = GameWord.create(game: g9, word: w25)

